/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: nattsol (https://sketchfab.com/nattsol)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/glasses-3d-model-74c1d202ac0249e39823e379e2b065e9
Title: Glasses 3D model
*/

import { useGLTF } from '@react-three/drei';
import { defaultControls, UseGLTFProps } from './constants';

import { useGSAP } from '@gsap/react';
import gsap from 'gsap';
import { RefObject } from 'react';
import glasses3d from '../../3dModels/glasses.glb';
// import { useControls } from 'leva';
// import { ScrollTrigger } from 'gsap/ScrollTrigger';

useGLTF.preload(glasses3d);

// gsap.registerPlugin(ScrollTrigger);

interface GlassesProps {
  targetViewRef: RefObject<HTMLDivElement | null>;
  selfRef: RefObject<null>;
  callbackFn: Function;
}

export function Glasses({ targetViewRef, selfRef, callbackFn }: GlassesProps) {
  // const controls = useControls(
  //   defaultControls([0, 0, 0], [0, 0, 0], [15, 15, 15])
  // );

  const controls = defaultControls([0, 0, 0], [0, 0, 0], [15, 15, 15]);

  useGSAP(() => {
    const timeline = gsap.timeline();

    !!selfRef?.current &&
      timeline
        .to(selfRef.current['rotation'], {
          y: 3.1,
          duration: 2
        })
        .to(selfRef.current['scale'], {
          x: 100,
          y: 100,
          z: 100,
          duration: 5
        })
        .call(() => {
          if (!targetViewRef?.current) {
            return;
          }

          targetViewRef.current.style.animation = 'image_blur 2s';
          targetViewRef.current.style.animationFillMode = 'forwards';
        })
        .to(selfRef.current['scale'], {
          x: 500,
          y: 500,
          z: 500,
          duration: 5
        })
        .call(() => callbackFn());
  });

  const { nodes, materials } = useGLTF(glasses3d) as unknown as UseGLTFProps;
  return (
    <group
      ref={selfRef}
      dispose={null}
      position={[
        controls['position.x'].value,
        controls['position.y'].value,
        controls['position.z'].value
      ]}
      rotation={[
        controls['rotation.x'].value,
        controls['rotation.y'].value,
        controls['rotation.z'].value
      ]}
      scale={[
        controls['scale.x'].value,
        controls['scale.y'].value,
        controls['scale.z'].value
      ]}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_5.geometry}
        material={materials.Frame}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.Lens}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_11.geometry}
        material={materials.Nosepads}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_14.geometry}
        material={materials.Temple}
        position={[0.068, 0.028, -0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_17.geometry}
        material={materials.Temple}
        position={[-0.068, 0.028, -0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_20.geometry}
        material={materials.Temple_tips}
        position={[0.068, 0.028, -0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_23.geometry}
        material={materials.Temple_tips}
        position={[-0.068, 0.028, -0.02]}
      />
    </group>
  );
}
